baseURL = "https://markautodetailing.co.id/"
languageCode = "id-id"
title = "Mark Auto Detailing"
theme = "stein"
sectionPagesMenu = "main"
disableHugoGeneratorInject = "true"

[menu]
[[menu.main]]  
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Nano Ceramic"
    url = "/nano-ceramic/"
    weight = 2
[[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    url = "/price-list/"
    weight = 6
[[menu.main]]
    name = "Interior Restoration"
    url = "/restorasi-interior/"
    weight = 3
[[menu.main]]
    name = "Coating Process"
    url = "/coating-process/"
    weight = 4
[[menu.main]]
    name = "Before After"
    url = "/before-after/"
    weight = 5
[[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 7